### ISSUE TITLE
Ukol c.1

### ISSUE THREAD

**Issue by BaraMarconova** [BaraMarconova/python-kurz-2022#1]
https://github.com/BaraMarconova/python-kurz-2022/blob/main/ukol-1.py

odezdavam ukol c.1

**Comment by lutydlitatova** [comment]
Báro, super řešení, díky 🙂 

Tip: Podmínku [na řádce 10](https://github.com/BaraMarconova/python-kurz-2022/blob/main/ukol-1.py#L10) bychom mohli ještě zjednodušit, `baliky[kod_baliku]` se vyhodnotí na `True` nebo `False`:

```python
  if baliky[kod_baliku]:
    print("Balík byl předán kurýrovi.")
  else:
    print("Balík zatím nebyl předán kurýrovi.")
```
