### ISSUE TITLE
ukol 9 zoo

### ISSUE THREAD

**Issue by BaraMarconova** [BaraMarconova/python-kurz-2022#12]
ahoj, uplne jsem zapomnela poslat ukol c.9 

https://github.com/BaraMarconova/python-kurz-2022/blob/main/ukol9_zoo.py

**Comment by lutydlitatova** [comment]
Super, díky!

Při nastavení indexu na jeden ze sloupců bys také mohla využít název sloupce, a fungovalo by to stejně, jako zadat pozici sloupce:

```py
zvirata_index = pandas.read_csv(r"C:\...adopce-zvirat.csv", delimiter=";", index_col=1)
```

```py
zvirata_index = pandas.read_csv(r"C:\...adopce-zvirat.csv", delimiter=";", index_col="nazev_cz")
```
