### ISSUE TITLE
ukol c.2

### ISSUE THREAD

**Issue by BaraMarconova** [BaraMarconova/python-kurz-2022#2]
https://github.com/BaraMarconova/python-kurz-2022/blob/main/ukol-2.py

odevzdavam ukol c2

**Comment by lutydlitatova** [comment]
Ahoj Báro @BaraMarconova , vypadá to na dobré cestě 🙂 Program teď vypisuje `Neznámý region` pokaždé, i u známých regionů. Je víc způsobů, jak na to, aby se hláška vypsala jen u neznámého regionu. Chceš některý z nich poradit?

Jinak mne napadá ještě spíš stylistická věc, tyto dvě podmínky:
```py
  if interested_region in (stat['region']):
    if (stat['region']) in interested_region :
```

můžeš nahradit jedinou, trochu se to tak zjednoduší:
```py
  if interested_region == stat['region']:
```

**Comment by lutydlitatova** [comment]
> jeste jsem se chtela zeptat, jestli je tam nejaka 'zkryta pamet' kdyz jsem vymazala cast s 'Neznámý region' a program jsem pustila znovu tak mi to nadale vypisovalo 'Neznámý region' i kdyz uz se v programu tyto slova vubec neobjevovala

Tohle se může stát, když se program neuloží, že se pustí jeho stará verze, ale jinak žádná skrytá paměť není 🙂 

Jinak k řešení, zkusím načrtnout dva způsoby:

První je vytvořit si prázdný seznam států, do kterého budeš postupně přidávat státy, pokud se trefíš do regionu. Po skončení cyklu se můžeš podívat, jestli je seznam prázdný, a  pokud ano, znamená to, že se jednalo o neznámý region.

Druhý způsob, který mne napadá, je vytvořit si nějakou proměnnou jako ukazatel toho, že máme známý region. Tu proměnnou si před cyklem nastavíme jako `False` (předpokládáme, že uživatel zadal neznámž region), a potom pokud narazíme na stát, který je ve správném regionu, tj který splňuje podmínku, tak jí přenastavíme na `True`. Pak zas po skončení cyklu koukneme na proměnnou, a podle její hodnoty vypíšeš "Neznámy region" nebo ne. 

Můžeš si jeden ze způsobů vybrat a zkusit naimplementovat 🙂

**Comment by BaraMarconova** [comment]
https://github.com/BaraMarconova/python-kurz-2022/blob/main/ukol-2.py

oprava ukolu 2

**Comment by lutydlitatova** [comment]
Ahoj Báro, skvělé, díky, píšu bod 👍 

V tvém řešení bychom mohly dvě věci zjednodušit (program by fungoval stejně):

Dvě podmínky nahradit za jednu (dělají to samé):
```python
for stat in staty:
  if interested_region == stat['region']:
    name = stat['name']
    staty_v_regionu[name] = name
```

A dokonce bychom nepotřebovaly ani `any`:
```python
if staty_v_regionu:
  print(staty_v_regionu)
else:
  print("Neznamy region")
```
