### ISSUE TITLE
ukol2 - bonus

### ISSUE THREAD

**Issue by BaraMarconova** [BaraMarconova/python-kurz-2022#3]
https://github.com/BaraMarconova/python-kurz-2022/blob/main/bonus_pokus2.py

**Comment by lutydlitatova** [comment]
Super řešení 🙂 👍 

Čistě stylistická věc je, že některé závorky nejsou potřeba:
```python
  if interested_region == stat['region']:
    subregion = stat['subregion']
    population = stat['population']
```
