### ISSUE TITLE
ukol 6+ bonus

### ISSUE THREAD

**Issue by BaraMarconova** [BaraMarconova/python-kurz-2022#7]
https://github.com/BaraMarconova/python-kurz-2022/blob/main/ukol6_auta.py

ahoj posilam ukol 6 s bonusem

**Comment by lutydlitatova** [comment]
Super 🙂 Je tam jen jedna drobnost, hodnoty jsou v tisících kilometrů, takže třeba hodnota 16.1 značí 16100 km.

**Comment by BaraMarconova** [comment]
tak jsem to jen vynasobila 1000, tam, kde prevadim carku na tecku (auta_prevod_cisla)

na konci jsem celkovy soucet prevedla na INT(), protoze v tomhle pripade nepotrebuji float


```
nazev_souboru = input("Zadej nazev souboru:")

with open(nazev_souboru) as vstup:
  auta = vstup.readlines()
auta_split = [auto.split() for auto in auta]
auta_prevod_cisla = [[auto[0], float(auto[1].replace(",","."))***1000**] for auto in auta_split]
print(auta_prevod_cisla)
soucet_km = sum([(auto[1]) for auto in auta_prevod_cisla])
print(**int(soucet_km)**)
```

**Comment by lutydlitatova** [comment]
👍
